### ISSUE TITLE
issues concerning logistic regression etc.

### ISSUE THREAD

**Issue by jalhackl** [xin-huang/sstar#23]
https://github.com/xin-huang/sstar/blob/fb56d01a1be884a63eb08442a93b92ebbb27ecb6/sstar/train.py#L49C1-L55

this seems to be the function signature of an older version

**Comment by jalhackl** [comment]
https://github.com/xin-huang/sstar/blob/fb56d01a1be884a63eb08442a93b92ebbb27ecb6/sstar/train.py#L20C1-L20C42

this function from sstar.preprocess doesn't exist (and also isn't used in train) - probably, it should simply be removed

**Comment by xin-huang** [comment]
Updated in this commit 8f47d0b92f2bacafad69877eaefb9aa2314d63dc
